name: AL-Go Tag Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*.*'

permissions:
  contents: read
  actions: read

jobs:
  tag_build:
    uses: microsoft/AL-Go-Actions/.github/workflows/CICD.yaml@main
    secrets: inherit
